services:
  - type: web
    name: saudi-science-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        fromEnv: TELEGRAM_TOKEN
      - key: TELEGRAM_CHANNEL_ID
        fromEnv: TELEGRAM_CHANNEL_ID
      - key: OPENAI_API_KEY
        fromEnv: OPENAI_API_KEY
      - key: RENDER
        value: true
